name: "Deploy"


on:
  workflow_run:
    workflows: [Nganu]
    types: [completed]
    branches: ["dev"]
jobs:
  deploy:
    name: "Deploy Releasez"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'app'
          runtime: 'nodejs18'
